model:
  name: LightningFFVAE
  args:
    embed_dim: 64
    depth: 8
    hidden_dim: 4096
    lr: 0.000251

data_module:
  function: create_data_module
  args:
    batch_size: 4096
    path: data/enc_moles.npy
    seed: 42
