model:
  name: YetAnotherVAELightning
  args:
    embed_dim: 128
    num_lstm_layers: 8
    lstm_hidden_dim: 512
    lr: 0.0003

data_module:
  function: create_data_module
  args:
    batch_size: 4096
    path: data/enc_moles.npy
    seed: 42
